### ISSUE TITLE
Search problem

### ISSUE THREAD

**Issue by omar1slam** [dsuarezv/satellite-tracker#5]
No searches seem to appear whatever I write in the search bar

**Comment by dsuarezv** [comment]
The demo is not working at the moment. The proxy I used to access the satellite database (cors-anywhere.herokuapp.com) has stopped working, so I'll have to figure another way to do that function.

**Comment by omar1slam** [comment]
So if I moved the satellite database offline it should run?

**Comment by dsuarezv** [comment]
Fixed in 45131607b278a7f49b7115a0329a8bd4b8ecbaea

**Comment by omar1slam** [comment]
Thanks you for fixing it. much appreciated
